### ISSUE TITLE
Wordpress 5.0.0 compatibility testing.

### ISSUE THREAD

**Issue by radius314** [radius314/bread#38]
WP 5.0.0 comes out November 19th.

Spin up an instance (possibly docker) with 5.0.0 RC1 and test out the plugin.  

Also 5.0.0 will require PHP 7.3.x

**Comment by radius314** [comment]
getting this error on WP5 activation

```
Fatal error: Uncaught Error: Call to undefined function get_current_screen() in /var/www/html/wp-content/plugins/bread/bread.php:90 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(288): Bread->my_register_mce_button(Array) #1 /var/www/html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /var/www/html/wp-includes/script-loader.php(492): apply_filters('mce_buttons', Array, 'editor') #3 /var/www/html/wp-includes/script-loader.php(559): wp_default_packages_inline_scripts(Object(WP_Scripts)) #4 /var/www/html/wp-includes/class-wp-hook.php(286): wp_default_packages(Object(WP_Scripts)) #5 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /var/www/html/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #7 /var/www/html/wp-includes/class.wp-scripts.php(148): do_action_ref_array('wp_default_scri...', Array) #8 /var/www/html/wp-includes/class.wp-scripts.php(131): WP_Scripts->init() #9 /var/www/html/wp-includes/functions.wp-scripts.php(23): WP_Scripts->__const in /var/www/html/wp-content/plugins/bread/bread.php on line 90```

**Comment by radius314** [comment]
completed compat testing against php 7.2 and wp 5 in unstable

**Comment by radius314** [comment]
completed in 1.8.0
